server:
  port: ${port:8080}
  max-http-header-size: 40MB


spring:
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  flyway:
    enabled: true
    # history ???? ?? ?? ??
    baseline-on-migrate: true
    locations:
      - classpath:/db/migration
    baseline-version: 1

dgs:
  graphql:
    schema-locations:
      - classpath*:schema/*.graphql*

error:
  log:
    config:
      filename: error

#??? ?????
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info,beans,conditions
        exclude: threaddump, heapdump
  endpoint:
    shutdown:
      enabled: true

logging:
  level:
    io.micrometer.core.instrument.logging.*: INFO